"""summary table

Revision ID: 36e3b46851d3
Revises: 
Create Date: 2023-11-15 18:22:21.250752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36e3b46851d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('x', sa.String(length=60), nullable=True),
    sa.Column('github', sa.String(length=60), nullable=True),
    sa.Column('linkedin', sa.String(length=60), nullable=True),
    sa.Column('website', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_id'), 'contact', ['id'], unique=False)
    op.create_table('development',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=60), nullable=False),
    sa.Column('institution', sa.String(length=60), nullable=False),
    sa.Column('location', sa.String(length=30), nullable=False),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_date', sa.String(length=30), nullable=False),
    sa.Column('end_date', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_development_id'), 'development', ['id'], unique=False)
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=60), nullable=False),
    sa.Column('location', sa.String(length=30), nullable=False),
    sa.Column('degree', sa.String(length=40), nullable=False),
    sa.Column('start_date', sa.String(length=30), nullable=False),
    sa.Column('end_date', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_id'), 'education', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.Column('link', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_id'), 'summary', ['id'], unique=False)
    op.create_table('technical_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('development_frameworks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version_control', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('containerization', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dbms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('BaaS_platform', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cloud_platform', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('others', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_skills_id'), 'technical_skills', ['id'], unique=False)
    op.create_table('work_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=60), nullable=False),
    sa.Column('location', sa.String(length=30), nullable=False),
    sa.Column('position', sa.String(length=40), nullable=False),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_date', sa.String(length=30), nullable=False),
    sa.Column('end_date', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_experience_id'), 'work_experience', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_experience_id'), table_name='work_experience')
    op.drop_table('work_experience')
    op.drop_index(op.f('ix_technical_skills_id'), table_name='technical_skills')
    op.drop_table('technical_skills')
    op.drop_index(op.f('ix_summary_id'), table_name='summary')
    op.drop_table('summary')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_education_id'), table_name='education')
    op.drop_table('education')
    op.drop_index(op.f('ix_development_id'), table_name='development')
    op.drop_table('development')
    op.drop_index(op.f('ix_contact_id'), table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###
